version: '3'

services:
    rundeck:
        image: ${RUNDECK_IMAGE:-rundeck/rundeck:SNAPSHOT}
        links:
          - oracle
        environment:
            RUNDECK_DATABASE_DRIVER: oracle.jdbc.driver.OracleDriver
            RUNDECK_DATABASE_DIALECT: org.rundeck.hibernate.RundeckOracleDialect
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:oracle:thin:@oracle:1521/orclpdb1.localdomain
        volumes:
          - ./lib:/home/rundeck/server/lib
          - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
        ports:
          - 4440:4440
    oracle:
        image: container-registry.oracle.com/database/enterprise:12.2.0.1-slim
        expose:
          - 1521
        volumes:
          - dbdata:/ORCL

volumes:
    dbdata: