version: '3'

services:
    rundeck:
        image: ${RUNDECK_IMAGE:-rundeck/rundeck:SNAPSHOT}
        volumes:
          - data:/home/rundeck/server/data
        ports:
          - 4440:4440

volumes:
    data: